name: Example Workflow  # 워크플로 이름

on:  # Event (워크플로를 트리거하는 조건)
  push:
    branches:
      - main  # main 브랜치에 코드가 푸시될 때 실행

jobs:  # Job (워크플로 내 작업 단위)
  example-job:
    runs-on: ubuntu-latest  # Runner (작업 실행 환경)

    steps:  # Step (Job 내의 실행 단계)
      - name: Checkout code  # Step 이름
        uses: actions/checkout@v3  # Action 사용 (코드 체크아웃)

      - name: Print Hello World
        run: echo "Hello, World!"  # 커스텀 명령어 실행